# = ProtocolSupportPocketStuff =
#  Enable / Disable / Configure
#   pocket-assisting features
#
# = Skins =
# PCtoPE      - Enables the caching and sending of Java edition skins to bedrock players.
# PEtoPC      - Enables the uploading of skins to mineskin.net to fake PE skins for PC players.
# cache-size  - Determines the maximum cachesize. The cache is needed for skins but can impact memory.
#               It is best to set it to roughly the size of your regular playerbase.
#               Unless skins are disabled do not set the size to 0!
# cache-rate  - Determines how long skins are cached. This will not impact skin change,
#               but determines how fast (in hours) the skins in the cache are cleaned 
#               and thus also need to be redownloaded if they are to be used again.
#               Unless skins are disabled do not set the rate to 0!
#
# = Pocket Packs =
# force-resources - Forces packs to the client, if the client rejects the resource pack, it will be kicked
# behavior-packs  - List with the file names of the resource packs
# resource-packs  - List with the file names of the resource packs
#
# (Behavior Packs and Resource Packs)
# Note: The packs are applied from the bottom to the top (in the same way PC/PE resource packs are applied).
# The last pack is applied first, then the next one, then the next one, and so on.
# This means the first pack in the list will override all changes from the subsequent packs
# !Packs must be added to ./plugins/ProtocolSupportPocketStuff/pocketpacks!
#
# = Hacks =
# middleclick - Enables using bukkit to fake middle click / blocks and entities pick.
# farplace    - Enables using bukkit to allow pocket to place blocks further than pc.
# holograms   - Enables experimental caching and "armor stand to player" replacement to support holograms for PE players.
# itemframes  - Enables experimental caching and mucking with packets to support itemframes for PE players.
# bossbars    - Enables experimental caching and mucking with packets to boss bars for PE players.
# player-heads-skins  - Options related to player heads with custom skins
#   skull-blocks      - Enables experimental caching, "player heads to players" replacement to support player heads with skins for PE players.
#   equipped-blocks   - Enables experimental caching, skin replacement to support equipped player heads with skins for PE players.
#
# = Logging =
# disable-colors - Disables console colors when logging if enabled.
# enable-debug   - Enables PSPS debug messages when enabled.
#
# !Do not change the config-version unless you know what you are doing!

skins:
 PCtoPE: true
 PEtoPC: true
 cache-size: 250
 cache-rate: 24
pocketpacks:
 force-resources: false
 behavior-packs: []
 resource-packs: []
hacks: 
 middleclick: true
 farplace: false
 holograms: true
 itemframes: false
 bossbars: false
 player-heads-skins:
  skull-blocks: false
  equipped-blocks: false
logging:
 disable-colors: false
 enable-debug: false
config-version: 4
