name: ProtocolSupportPocketStuff
main: protocolsupportpocketstuff.ProtocolSupportPocketStuff
depend: [ProtocolSupport]
version: 1.0
author: ProtocolSupportTeam
commands:
  protocolsupportpocketstuff:
    description: All ProtocolSupportPocketStuff commands
    aliases: [psps]
    usage: '/protocolsupportpocketstuff help'